controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ["Wheel_FL_joint", "Wheel_RL_joint"]
    right_wheel_names: ["Wheel_FR_joint", "Wheel_RR_joint"]

    wheel_separation: 0.88
    wheel_radius: 0.35

    # Add these important parameters
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_limited_velocity: true
    use_stamped_vel: false
    enable_odom_tf: true
    
    # Frame names
    base_frame_id: base_footprint
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0

joint_state_broadcaster:
  ros__parameters: {}